Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using LibraryWebMVC.Interfaces;
using LibraryWebMVC.Models;
using Newtonsoft.Json;
using LibraryWebMVC.Utils;
using LibraryWebMVC.ViewModels;

namespace LibraryWebMVC.Controllers
{
    public class AdminController : Controller
    {
        private readonly IApiRequestService _apiRequest;
        private readonly IApiAuthService _apiAuthService;

        private static string Api { get; set; } = "";
        private static int Id { get; set; } = 0;

        public AdminController(IApiRequestService apiRequest, IApiAuthService apiAuthService)
        {
            _apiRequest = apiRequest;
            _apiAuthService = apiAuthService;
        }

        public async Task<IActionResult> AdminToolsAsync()
        {

            var authorizedRole = await _apiAuthService.GetAuthorizedRole();
            if (authorizedRole is not null)
            {
                var booksJSON = await _apiRequest.Get("Books");
                var authorsJSON = await _apiRequest.Get("Authors");


                if (booksJSON is null || authorsJSON is null)
                {
                    ViewBag.ErrorMessage = CommonErrorMessage;
                    return View();
                }
                else
                {
                    var booksList = JsonConvert.DeserializeObject<List<Book>>(booksJSON);
                    var authorsList = JsonConvert.DeserializeObject<List<Author>>(authorsJSON);

                    LibViewModel models = new LibViewModel
                    {
                        Books = booksList,
                        Authors = authorsList
                    };

                    return View(models);
                }
       
            }

            return Redirect("~/Admin/AccessDenied");

        }

        public IActionResult AccessDeniedAsync()
        {
            return View();
        }


        public async Task<IActionResult> EditAsync(string api, int id, string errorMessage = null)
        {

            var authorizedRole = await _apiAuthService.GetAuthorizedRole();
            if (authorizedRole is not null && authorizedRole.Equals(AdminRole))
            {
                if (id == 0)
                {
                    return Redirect("~/Admin/AdminTools");
                }
                var objectJSON = await _apiRequest.Get(api, id);

                if (objectJSON is null)
                {

                    ViewBag.ErrorMessage = CommonErrorMessage;
                    return Redirect("~/Admin/AdminTools");
                }
                else
                {
                    CollectionItems bookCollectionItem;
                    if(api.Equals("Authors"))
                    {
                        var author = JsonConvert.DeserializeObject<Author>(objectJSON);

                        bookCollectionItem = new CollectionItems { Author = author, Book = null };
                        ViewBag.IsAuthor = true;
                        
                    }
                    else
                    {
                        
                        var book = JsonConvert.DeserializeObject<Book>(objectJSON);
                        
                        bookCollectionItem = new CollectionItems { Author = null, Book = book };
                        ViewBag.IsAuthor = false;
                    }

                    Api = api;
                    Id = id;

                    if(errorMessage is not null) 
                        ViewBag.ErrorMessage = errorMessage;

                    return View(bookCollectionItem);
                }

            }
            return Redirect("~/Admin/AccessDenied");
           
        }

        [HttpPost]
        public async Task<IActionResult> EditBookAsync(Book book)
        {
            var authorizedRole = await _apiAuthService.GetAuthorizedRole();
            if (authorizedRole is not null && authorizedRole.Equals(AdminRole))
            {
                var objectJSON = await _apiRequest.Get(Api, Id);

                if (objectJSON is null)
                {
                    ViewBag.ErrorMessage = CommonErrorMessage;
                    return View();
                }

                var stringResponse = await _apiRequest.Put(Api, Id, book);
                if (!string.IsNullOrEmpty(stringResponse))
                {
                    return RedirectToAction("Edit", new { api = Api, id = Id, errorMessage = stringResponse });
                }

                return Redirect("~/Admin/AdminTools");
            }

            return Redirect("~/Admin/AccessDenied");
        }

        [HttpPost]
        public async Task<IActionResult> EditAuthorAsync(Author author)
        {
            var authorizedRole = await _apiAuthService.GetAuthorizedRole();
            if (authorizedRole is not null && authorizedRole.Equals(AdminRole))
            {
                var objectJSON = await _apiRequest.Get(Api, Id);

                if (objectJSON is null)
                {
                    ViewBag.ErrorMessage = CommonErrorMessage;
                    return View();
                }

                var stringResponse = await _apiRequest.Put(Api, Id, author);
                if (!string.IsNullOrEmpty(stringResponse))
                {
                    return RedirectToAction("Edit", new { api = Api, id = Id, errorMessage = stringResponse });
                }

                return Redirect("~/Admin/AdminTools");

            }

            return Redirect("~/Admin/AccessDenied");
        }

        public async Task<IActionResult> DeleteAsync(string api, int id)
        {

            var authorizedRole = await _apiAuthService.GetAuthorizedRole();
            if (authorizedRole is not null && authorizedRole.Equals(AdminRole))
            {
                if (id == 0)
                {
                    return Redirect("~/Admin/AdminTools");
                }
                var objectJSON = await _apiRequest.Get(api, id);

                if (objectJSON is null)
                {
                    return Redirect("~/Admin/AdminTools");
                }
                var stringMessage = _apiRequest.Delete(api, id);

                if (stringMessage is not null)
                    ViewBag.ErrorMessage = stringMessage;

                return Redirect("~/Admin/AdminTools");
            }

            return Redirect("~/Admin/AccessDenied");

        }


        public async Task<IActionResult> CreateAsync(string api, string errorMessage = null)
        {

            var authorizedRole = await _apiAuthService.GetAuthorizedRole();
            if (authorizedRole is not null && authorizedRole.Equals(AdminRole))
            {
                Api = api;

                if (api.Equals("Authors"))
                {
                    ViewBag.IsAuthor = true;
                }
                else
                {
                    ViewBag.IsAuthor = false;
                }

                if (errorMessage is not null)
                    ViewBag.ErrorMessage = errorMessage;

                return View();

            }

            return Redirect("~/Admin/AccessDenied");

        }

        [HttpPost]
        public async Task<IActionResult> CreateBookAsync(Book book)
        {
            var authorizedRole = await _apiAuthService.GetAuthorizedRole();
            if (authorizedRole is not null && authorizedRole.Equals(AdminRole))
            {
                var stringResponse = await _apiRequest.Post(Api, book);
                if (!string.IsNullOrEmpty(stringResponse))
                {
                    return RedirectToAction("Create", new { api = Api, errorMessage = stringResponse });
                }

                return Redirect("~/Admin/AdminTools");

            }

            return Redirect("~/Admin/AccessDenied");
        }

        [HttpPost]
        public async Task<IActionResult> CreateAuthorAsync(Author author)
        {
            var authorizedRole = await _apiAuthService.GetAuthorizedRole();
            if (authorizedRole is not null && authorizedRole.Equals(AdminRole))
            {
                var stringResponse = await _apiRequest.Post(Api, author);
                if (!string.IsNullOrEmpty(stringResponse))
                {
                    return RedirectToAction("Create", new { api = Api, errorMessage = stringResponse });
                }

                return Redirect("~/Admin/AdminTools");

            }

            return Redirect("~/Admin/AccessDenied");
        }

    }
}

Controllers/LoginController.cs
using LibraryWebMVC.Interfaces;
using LibraryWebMVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace LibraryWebMVC.Controllers
{
    public class LoginController : Controller
    {

        private readonly IApiRequestService _apiRequest;

        public LoginController(IApiRequestService apiRequest)
        {
            _apiRequest = apiRequest;
        }
        public IActionResult LogIn()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> LogInAsync(UserLogin user)
        {

            var response = await _apiRequest.PostRequestResponseMessage(LoginApi, user);

            if (response.IsSuccessStatusCode)
            {
                var resToken = response.Content.ReadAsStringAsync().Result;

                Response.Cookies.Append("X-Access-Token", resToken, new CookieOptions()
                {
                    HttpOnly = true,
                    SameSite = SameSiteMode.Strict,
                    Secure = true,
                    Expires = DateTime.Now.AddMinutes(15)
                });
                return Redirect("/Home/Catalog");
            }
            
            ViewBag.ErrorMessage = "Incorrect username or password";
            return View();
        }

        public IActionResult LogOut()
        {
            Response.Cookies.Delete("X-Access-Token");

            return Redirect("/Home/Index");
        }
    }
}

Controllers/RegisterController.cs
using LibraryWebMVC.Interfaces;
using LibraryWebMVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace LibraryWebMVC.Controllers
{
    public class RegisterController : Controller
    {

        private readonly IApiRequestService _apiRequest;

        public RegisterController(IApiRequestService apiRequest)
        {
            _apiRequest = apiRequest;
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> RegisterAsync(User user)
        {
            var response = await _apiRequest.PostRequestResponseMessage(UserApi, user);

            if (response.IsSuccessStatusCode)
            {
                return Redirect("/Home/Catalog");
            }
            string errorMessage = await response.Content.ReadAsStringAsync();
            ViewBag.ErrorMessage = errorMessage.Trim('"');
           
            
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
@using LibraryWebMVC.Interfaces
@inject IApiAuthService _apiAuthservice

@{
    ViewBag.IsAuthorized = false;
    ViewBag.IsAdmin = false;

    var authorizedRole = await _apiAuthservice.GetAuthorizedRole();
    if(authorizedRole is not null)
    {
        ViewBag.IsAuthorized = true;

        if (authorizedRole.Equals(AdminRole))
        {
            ViewBag.IsAdmin = true;
        }

    }

}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Library</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LibraryWebMVC.styles.css" asp-append-version="true" />
    <link type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LibraryWebMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Catalog">Catalog</a>
                        </li>
                        @if(@ViewBag.IsAdmin)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="AdminTools">AdminTools</a>
                            </li>
                        }
                    </ul>
                    <ul class="nav justify-content-end">
                        @if(@ViewBag.IsAuthorized)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="LogOut">Log Out</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Register" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="LogIn">Log In</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Library
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
   
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>